## Procedural world generator: builds a stylized Earth map made of ~500 hex provinces.
extends Node

const Province = preload("res://scripts/province.gd")
const Country = preload("res://scripts/country.gd")
const ArmyUnit = preload("res://scripts/unit.gd")
const Character = preload("res://scripts/character.gd")

const HEX_SIZE: float = 30.0 # circumradius (point-to-point/2)

# Auto-generated by tools/gen_landmask.py — do not hand-edit.
const LANDMASK_W: int = 240
const LANDMASK_H: int = 120
const LANDMASK_HEX: String = \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000001ffff80000000000000000000000000000000000" + \
	"000000000000000000003ffffc0000000000000000000000000000000000" + \
	"000000000000000000003fffff0000000000000000000000000000000000" + \
	"000000000000000000007fffff8000000000000000000000000000000000" + \
	"00000000000000000000ffffffe000000000000000000000000000002000" + \
	"00000000000000000000ffffffe000000000000000000000000007ffffff" + \
	"00000000000000002000ffffffe00000000000000000000000ffffffffff" + \
	"00000000000007fff8007fffffc0000000000000000000007fffffffffff" + \
	"000000003fffffffff007fffffc0000000ffffff9fe0003fffffffffffff" + \
	"0003ffffffffffffffc07fffffc0001fffffffffffffffffffffffffffff" + \
	"000fffffffffffffffe03fffff00001ffffffffffffffffffffffffffff8" + \
	"003fffffffffffffffe03ffffe00001fffffffffffffffffffffffffffc0" + \
	"00fffffffffffffffff01ffff9fe001ffffffffffffffffffffffffffe00" + \
	"007ffffffffffffffff80ffff1ff000ffffffffffffffffffffffffff000" + \
	"003ffffffffffffffffc07ffc040000fffffffffffffffffffffffffc000" + \
	"001ffffffffffffffffc07ff80000007fffffffffffffffffffffffe0000" + \
	"000ffffffffffffffffe03fe00000f07fffffffffffffffffffffff80000" + \
	"0007fffffffffffffffe000000000f0fffffffffffffffffffffffe00000" + \
	"00007fffffffffffffff000000000f8fffffffffffffffffffffff000000" + \
	"000003ffffffffffffff000000007f9ffffffffffffffffffffffc000000" + \
	"0000003fffffffffffff000000007fbffffffffffffffffffffff8000000" + \
	"00000003ffffffffffff800000007ffffffffffffffffffffffff0000000" + \
	"00000001ffffffffffff8000000007fffffffffffffffffff80020000000" + \
	"00000001ffffffffffffc00000000fffffffffffffffffffc00000000000" + \
	"00000000ffffffffffffc00000003ffffffffffffffffffe000000000000" + \
	"00000000fffffffffffe000000003ffffffffffffffff800000000000000" + \
	"000000007ffffffffff0000000007fffffffffffffffff00000003800000" + \
	"000000007ffffffffff0000000007ff3f7ffffffffffffe0000007000000" + \
	"000000003ffffffffff0000000007fe0f01ffffffffffffe000006000000" + \
	"000000001ffffffffff0000000003fc0383ffffffffffffffe000c000000" + \
	"000000000fffffffffc0000000003f80003fffffffffffffffde10000000" + \
	"000000000fffffffff00000000003e000003ffffffffffffffde30000000" + \
	"0000000007fffffffc000000000038020003ffffffffffffffce60000000" + \
	"0000000001fffffff80000000000001fe003e7ffffffffffffcf80000000" + \
	"0000000000fffffff0000000000000fffe03e3ffffffffffffc200000000" + \
	"00000000003fffffe000000000000fffffe3c1ffffffffffffc000000000" + \
	"00000000001fffffc000000000007fffffffc0ffffffffffffc000000000" + \
	"000000000007ffffc00000000000fffffffffe3ffcffffffffc000000000" + \
	"000000000003ffffc00000000001ffffffffff8ffdfff87fff8000000000" + \
	"000000000000ffff800000000001ffffffffffe083fffc3fff8000000000" + \
	"0000000000007ffe000000000003fffffffffff007fff803ff8000000000" + \
	"0000000000001ffc000000000007fffffffffff000fff900400000000000" + \
	"0000000000003f0000000000000ffffffffffff8007ff1fe000000000000" + \
	"0000000000003f8000000000000ffffffffffffc007fe1ff008000000000" + \
	"0000000000003fe000000000000ffffffffffff8003fc0ff00e000000000" + \
	"000000000000003c00000000000ffffffffffff8001f80ff81f800000000" + \
	"000000000000000e00000000000ffffffffffff0001f00ff81f800000000" + \
	"000000000000000700000000000fffffffffffc0000f00ff81f800000000" + \
	"0000000000000001bf800000000fffffffffffc0000e007f83f800000000" + \
	"0000000000000000ffff80000003ffffffffffc00006007f03f800000000" + \
	"00000000000000007fffe0000001ffffffffffe00004007e01f800000000" + \
	"00000000000000003ffff80000007fffffffffe00000007c01f800000000" + \
	"00000000000000003ffffe0000000fffffffffe00000017c008000000000" + \
	"00000000000000003fffff000000003fffffffe0000001f8fe0000000000" + \
	"00000000000000003fffffc00000001fffffffe0000001ffff8000000000" + \
	"00000000000000003fffffe00000001fffffffc0000001ffffe000000000" + \
	"00000000000000003ffffff80000000fffffff80000001fffff080000000" + \
	"00000000000000003ffffffc0000000ffffffe00000001fffffcf0000000" + \
	"00000000000000003fffffff00000007fffffc00000001fffffffe000000" + \
	"00000000000000003fffffff80000007fffff800000001ffffffffc00000" + \
	"00000000000000003fffffff80000007fffff800000001fffffffff80000" + \
	"00000000000000003fffffff80000003fffff000000000000ffffff80000" + \
	"00000000000000003fffffff80000003fffff00000000000001007f80000" + \
	"00000000000000003fffffff80000003fffff0000000000000000e000000" + \
	"00000000000000003fffffff80000001fffff8000000000000003f000000" + \
	"00000000000000007fffffff80000001ffffee00000000000000ff000000" + \
	"00000000000000007fffffff80000001ffffe7c0000000000003ff800000" + \
	"00000000000000007fffffff80000000ffffe7c000000000000fffc00000" + \
	"00000000000000007fffffff80000000ffffc7c000000000003fffe00000" + \
	"00000000000000007fffffff80000000ffffc7c00000000001ffffe00000" + \
	"00000000000000007fffffff800000007fffc3c0000000000ffffff00000" + \
	"00000000000000003fffffff800000007fff83c0000000000ffffff80000" + \
	"00000000000000003fffffff000000003fff03c0000000000ffffffc0000" + \
	"00000000000000003fffffff000000003ffe0000000000000ffffffc0000" + \
	"00000000000000001fffffff000000003ffe0000000000000ffffffc0000" + \
	"00000000000000001ffffffe000000001ffc0000000000000ffffffc0000" + \
	"00000000000000001ffffffe000000001ff80000000000000ffffff80000" + \
	"00000000000000001ffffffe000000000fe00000000000000ffffff80000" + \
	"00000000000000000ffffffc000000000f800000000000000ffffff80020" + \
	"00000000000000000ffffffc0000000000000000000000000003fff80030" + \
	"00000000000000000fffffe000000000000000000000000000007f80003c" + \
	"00000000000000000ffffe0000000000000000000000000000000800007e" + \
	"000000000000000007fff00000000000000000000000000000000000007e" + \
	"000000000000000007f80000000000000000000000000000000000e0007c" + \
	"000000000000000007f00000000000000000000000000000000000e0007c" + \
	"000000000000000007f00000000000000000000000000000000000e000f8" + \
	"000000000000000003e000000000000000000000000000000000000000f8" + \
	"000000000000000003e00000000000000000000000000000000000000000" + \
	"000000000000000003e00000000000000000000000000000000000000000" + \
	"000000000000000001c00000000000000000000000000000000000000000" + \
	"000000000000000001c00000000000000000000000000000000000000000" + \
	"000000000000000000800000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"000000000000000000000000000000000000000000000000000000000000" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" + \
	"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

## Decoded at generate() time — hex string → packed bit array for fast lookup.
## 1 byte per mask cell (0 = sea, 1 = land) so hot-path lookup is just an array
## index.
var _landmask: PackedByteArray = PackedByteArray()

func _build_landmask() -> void:
	if _landmask.size() == LANDMASK_W * LANDMASK_H:
		return
	var packed := PackedByteArray()
	packed.resize(LANDMASK_W * LANDMASK_H)
	var hex: String = LANDMASK_HEX
	var chars_per_row: int = LANDMASK_W / 4
	for y in range(LANDMASK_H):
		var row_hex: String = hex.substr(y * chars_per_row, chars_per_row)
		for cx in range(chars_per_row):
			var nibble: int = ("0x" + row_hex.substr(cx, 1)).hex_to_int()
			for b in range(4):
				var bit: int = (nibble >> (3 - b)) & 1
				packed[y * LANDMASK_W + cx * 4 + b] = bit
	_landmask = packed

## World coord (0..MAP_W, 0..MAP_H) treated as equirectangular projection:
##   x == 0 -> lon -180,  x == MAP_W   -> lon +180
##   y == 0 -> lat  +90,  y == MAP_H   -> lat  -90
## The landmask is sampled directly — bit == 1 is land.
func _is_land(p: Vector2) -> bool:
	if _landmask.is_empty():
		_build_landmask()
	var mx: int = int(p.x / GameState.MAP_W * float(LANDMASK_W))
	var my: int = int(p.y / GameState.MAP_H * float(LANDMASK_H))
	mx = clamp(mx, 0, LANDMASK_W - 1)
	my = clamp(my, 0, LANDMASK_H - 1)
	return _landmask[my * LANDMASK_W + mx] == 1

func _hex_polygon(center: Vector2, size: float, jitter_seed: int) -> PackedVector2Array:
	# Pointy-top hex. Slight per-vertex jitter for organic look (deterministic per cell).
	var pts := PackedVector2Array()
	var r := RandomNumberGenerator.new()
	r.seed = jitter_seed
	for i in range(6):
		var ang: float = deg_to_rad(60.0 * i - 30.0)
		var jx: float = r.randf_range(-0.18, 0.18) * size
		var jy: float = r.randf_range(-0.18, 0.18) * size
		pts.append(center + Vector2(cos(ang) * size + jx, sin(ang) * size + jy))
	return pts

func _pick_terrain(center: Vector2) -> int:
	# Latitudinal climate: poles tundra, mid temperate, equator jungle/desert.
	var y_norm: float = center.y / GameState.MAP_H # 0=top
	var lat_factor: float = abs(y_norm - 0.5) * 2.0 # 0=equator,1=pole
	var rng := RandomNumberGenerator.new()
	rng.seed = int(center.x * 91.0 + center.y * 17.0)
	var roll: float = rng.randf()
	if lat_factor > 0.75:
		return Province.Terrain.TUNDRA
	if lat_factor < 0.18:
		# Tropical band
		if roll < 0.35:
			return Province.Terrain.JUNGLE
		if roll < 0.60:
			return Province.Terrain.DESERT
		return Province.Terrain.PLAINS
	if lat_factor < 0.32 and roll < 0.5:
		return Province.Terrain.DESERT
	# Temperate / cold-temperate
	if roll < 0.10:
		return Province.Terrain.MOUNTAINS
	if roll < 0.25:
		return Province.Terrain.HILLS
	if roll < 0.50:
		return Province.Terrain.FOREST
	if roll < 0.65:
		return Province.Terrain.STEPPE
	return Province.Terrain.PLAINS

const SEA_NAMES: Array = [
	"Northern Ocean", "Western Sea", "Eastern Ocean", "Inland Sea", "Southern Sea",
	"Great Strait", "Open Waters", "Coastal Waters", "Deep Channel", "Distant Sea",
]

func _gen_sea_name(idx: int) -> String:
	var rng := RandomNumberGenerator.new()
	rng.seed = idx * 4099 + 31
	return String(SEA_NAMES[rng.randi_range(0, SEA_NAMES.size() - 1)])

func _gen_province_name(idx: int) -> String:
	var roots: Array = GameState.names_db.get("province_roots", ["Tarn"])
	var prefixes: Array = GameState.names_db.get("province_prefixes", [""])
	# Use a local RNG so we don't reseed the global GameState.rng (which would
	# make all subsequent province generation deterministic on the same seed).
	var name_rng := RandomNumberGenerator.new()
	name_rng.seed = idx * 7919 + 13
	var root: String = String(roots[name_rng.randi_range(0, roots.size() - 1)])
	if name_rng.randf() < 0.35 and prefixes.size() > 0:
		var pref: String = String(prefixes[name_rng.randi_range(0, prefixes.size() - 1)])
		return "%s %s" % [pref, root]
	return root

func generate(starting_era: String) -> void:
	GameState.reset()
	GameState.current_era = starting_era
	var era_def: Dictionary = GameState.eras_db.get(starting_era, {})
	GameState.year = int(era_def.get("year_start", -500))
	GameState.month = 1
	GameState.day = 1

	var hex_w: float = sqrt(3.0) * HEX_SIZE
	var hex_v: float = 1.5 * HEX_SIZE
	var rows: int = int(GameState.MAP_H / hex_v) + 1
	var cols: int = int(GameState.MAP_W / hex_w) + 1

	# Track which provinces exist at which (col,row) for neighbour lookup.
	var grid: Dictionary = {} # Vector2i(col,row) -> province id

	for r in range(rows):
		for c in range(cols):
			var x: float = c * hex_w + (0.5 * hex_w if r % 2 == 1 else 0.0)
			var y: float = r * hex_v
			var center := Vector2(x, y)
			if center.x < HEX_SIZE * 0.4 or center.x > GameState.MAP_W - HEX_SIZE * 0.4:
				continue
			if center.y < HEX_SIZE * 0.4 or center.y > GameState.MAP_H - HEX_SIZE * 0.4:
				continue
			var is_land: bool = _is_land(center)
			var p := Province.new()
			p.id = GameState.provinces.size()
			p.center = center
			p.polygon = _hex_polygon(center, HEX_SIZE, p.id * 17 + 5)
			if is_land:
				p.terrain = _pick_terrain(center)
				p.development = GameState.rng.randi_range(1, 5)
				p.population = p.development * 1000 + GameState.rng.randi_range(0, 800)
				p.name = _gen_province_name(p.id)
				p.is_sea = false
			else:
				p.terrain = Province.Terrain.SEA
				p.development = 0
				p.population = 0
				p.name = _gen_sea_name(p.id)
				p.is_sea = true
			GameState.provinces.append(p)
			grid[Vector2i(c, r)] = p.id

	# Compute hex neighbours.
	# Pointy-top, odd-r offset coordinates: even rows / odd rows have different deltas.
	var even_neighbors := [Vector2i(-1, 0), Vector2i(1, 0), Vector2i(0, -1), Vector2i(-1, -1), Vector2i(0, 1), Vector2i(-1, 1)]
	var odd_neighbors  := [Vector2i(-1, 0), Vector2i(1, 0), Vector2i(1, -1),  Vector2i(0, -1),  Vector2i(1, 1),  Vector2i(0, 1)]
	for key in grid.keys():
		var pid: int = grid[key]
		var deltas = even_neighbors if key.y % 2 == 0 else odd_neighbors
		var neigh: Array[int] = []
		for d in deltas:
			var nb: Variant = grid.get(key + d)
			if nb != null:
				neigh.append(int(nb))
		GameState.provinces[pid].neighbors = neigh

	# Mark coastal land provinces (have at least one sea neighbour) and
	# upgrade their terrain tint to COAST when they would otherwise be plains.
	var land_count: int = 0
	var sea_count: int = 0
	for p in GameState.provinces:
		if p.is_sea:
			sea_count += 1
			continue
		land_count += 1
		for nb_id in p.neighbors:
			var np: Province = GameState.provinces[int(nb_id)]
			if np != null and np.is_sea:
				p.is_coast = true
				if p.terrain == Province.Terrain.PLAINS:
					p.terrain = Province.Terrain.COAST
				break

	GameState.log_event("Generated %d land + %d sea provinces." % [land_count, sea_count])

	_assign_resources()

	_assign_starting_countries(starting_era)

	GameState.log_event("World ready: %s era starts in %d." % [str(era_def.get("name", starting_era)), GameState.year])
	GameState.world_ready.emit()

func _assign_resources() -> void:
	# Roughly 40% of land provinces get an economic resource based on terrain.
	# Coastal land additionally has a higher chance of fish.
	for p in GameState.provinces:
		if p.is_sea:
			continue
		if GameState.rng.randf() > 0.45:
			continue
		var r: String = ""
		match p.terrain:
			Province.Terrain.PLAINS, Province.Terrain.STEPPE:
				r = ["grain", "horses", "wool"][GameState.rng.randi_range(0, 2)]
			Province.Terrain.HILLS, Province.Terrain.MOUNTAINS:
				r = ["iron", "stone", "gold_ore"][GameState.rng.randi_range(0, 2)]
			Province.Terrain.FOREST:
				r = ["wood", "fur"][GameState.rng.randi_range(0, 1)]
			Province.Terrain.JUNGLE:
				r = ["spices", "wood"][GameState.rng.randi_range(0, 1)]
			Province.Terrain.DESERT:
				r = "salt"
			Province.Terrain.TUNDRA:
				r = "fur"
			Province.Terrain.COAST:
				r = "fish"
			_:
				r = ""
		if p.is_coast and r == "" and GameState.rng.randf() < 0.5:
			r = "fish"
		p.resource = r

func _assign_starting_countries(starting_era: String) -> void:
	var era_def: Dictionary = GameState.eras_db.get(starting_era, {})
	var starters: Array = era_def.get("starting_countries", [])
	var ruler_pool_m: Array = GameState.names_db.get("ruler_names_male", ["Ruler"])
	var ruler_pool_f: Array = GameState.names_db.get("ruler_names_female", ["Ruler"])
	var advisor_titles: Array = GameState.names_db.get("advisor_titles", ["Chancellor"])
	var general_titles: Array = GameState.names_db.get("general_titles", ["Marshal"])
	var trait_keys: Array = GameState.traits_db.keys()

	for cid in starters:
		var def: Dictionary = GameState.countries_db.get(cid, {})
		if def.is_empty():
			continue
		var c := Country.new()
		c.id = cid
		c.name = String(def.get("name", cid))
		var col: Array = def.get("color", [0.5, 0.5, 0.5])
		c.color = Color(col[0], col[1], col[2])
		c.era = String(def.get("era", starting_era))
		c.primary_culture = String(def.get("culture", "generic"))
		c.state_religion = String(def.get("religion", "pagan"))
		var gov_str: String = String(def.get("government", "MONARCHY"))
		c.government = Country.Government[gov_str] if gov_str in Country.Government else Country.Government.MONARCHY
		c.gold = 200.0
		c.manpower_pool = 8000.0
		c.legitimacy = 1.0
		c.stability = 0.0
		GameState.countries[cid] = c

		# Find provinces in country's region rect and assign as core territory.
		var region: Dictionary = GameState.regions_db.get(String(def.get("region", "")), {})
		var rx: float = float(region.get("x", -1))
		var ry: float = float(region.get("y", -1))
		var rw: float = float(region.get("w", 0))
		var rh: float = float(region.get("h", 0))
		var assigned_provinces: Array[int] = []
		if rx >= 0:
			for p in GameState.provinces:
				if p.is_sea:
					continue
				if p.owner_id != "" or p.center.x < rx or p.center.x >= rx + rw:
					continue
				if p.center.y < ry or p.center.y >= ry + rh:
					continue
				p.owner_id = cid
				p.culture = c.primary_culture
				p.religion = c.state_religion
				p.core_of.append(cid)
				assigned_provinces.append(p.id)
		# Fallback: if no provinces landed in the region rect (landmask gap),
		# grab the 3 nearest unassigned land provinces to the region centre so
		# this starter isn't a ghost country. This keeps all eras playable even
		# as the landmask is refined.
		if assigned_provinces.is_empty() and rx >= 0:
			var region_center := Vector2(rx + rw * 0.5, ry + rh * 0.5)
			var candidates: Array = []
			for p in GameState.provinces:
				if p.is_sea or p.owner_id != "":
					continue
				candidates.append({"id": p.id, "d2": p.center.distance_squared_to(region_center)})
			candidates.sort_custom(func(a, b): return a.d2 < b.d2)
			for i in range(min(3, candidates.size())):
				var p: Province = GameState.provinces[int(candidates[i].id)]
				p.owner_id = cid
				p.culture = c.primary_culture
				p.religion = c.state_religion
				p.core_of.append(cid)
				assigned_provinces.append(p.id)
			if assigned_provinces.size() > 0:
				GameState.log_event("Region '%s' missed landmask; seeded %s at nearest land." % [String(def.get("region", "")), cid])
		c.province_ids = assigned_provinces
		# Capital = highest-development province (or first).
		if assigned_provinces.size() > 0:
			var cap_id: int = assigned_provinces[0]
			var best_dev: int = -1
			for pid in assigned_provinces:
				var pp: Province = GameState.provinces[pid]
				if pp.development > best_dev:
					best_dev = pp.development
					cap_id = pid
			c.capital_id = cap_id
			GameState.provinces[cap_id].is_capital = true
			GameState.provinces[cap_id].development = max(GameState.provinces[cap_id].development, 6)
			# Capitals start with a small fort so enemy conquests require a siege.
			GameState.provinces[cap_id].fort_level = 1

		# Spawn ruler + advisors + generals.
		var ruler_male: bool = GameState.rng.randf() < 0.85
		var rname: String = String((ruler_pool_m if ruler_male else ruler_pool_f).pick_random())
		var ruler := Character.new()
		ruler.name = rname + " I"
		ruler.country_id = cid
		ruler.role = Character.Role.RULER
		ruler.age = GameState.rng.randi_range(25, 55)
		ruler.martial = GameState.rng.randi_range(0, 5)
		ruler.diplomacy = GameState.rng.randi_range(0, 5)
		ruler.stewardship = GameState.rng.randi_range(0, 5)
		ruler.intrigue = GameState.rng.randi_range(0, 5)
		ruler.learning = GameState.rng.randi_range(0, 5)
		ruler.traits = _pick_traits(trait_keys, 2)
		c.ruler_id = GameState.add_character(ruler)

		for ai in range(3):
			var adv := Character.new()
			adv.name = String(ruler_pool_m.pick_random()) + " " + String(advisor_titles[ai % advisor_titles.size()])
			adv.country_id = cid
			adv.role = Character.Role.ADVISOR
			adv.age = GameState.rng.randi_range(28, 65)
			adv.martial = GameState.rng.randi_range(0, 5)
			adv.diplomacy = GameState.rng.randi_range(0, 5)
			adv.stewardship = GameState.rng.randi_range(0, 5)
			adv.intrigue = GameState.rng.randi_range(0, 5)
			adv.learning = GameState.rng.randi_range(0, 5)
			adv.traits = _pick_traits(trait_keys, 1)
			c.advisor_ids.append(GameState.add_character(adv))

		for gi in range(2):
			var gen := Character.new()
			gen.name = String(ruler_pool_m.pick_random()) + " " + String(general_titles[gi % general_titles.size()])
			gen.country_id = cid
			gen.role = Character.Role.GENERAL
			gen.age = GameState.rng.randi_range(30, 60)
			gen.martial = GameState.rng.randi_range(2, 6)
			gen.diplomacy = GameState.rng.randi_range(0, 4)
			gen.stewardship = GameState.rng.randi_range(0, 4)
			gen.intrigue = GameState.rng.randi_range(0, 4)
			gen.learning = GameState.rng.randi_range(0, 4)
			gen.traits = _pick_traits(trait_keys, 1)
			c.general_ids.append(GameState.add_character(gen))

		# Starting army: 2 stacks of basic era units in capital.
		var starter_unit: String = _starter_unit_for(c.era)
		for i in range(2):
			var u := ArmyUnit.new()
			u.owner_id = cid
			u.type_id = starter_unit
			u.name = "%s Army %d" % [c.name, i + 1]
			u.province_id = c.capital_id
			u.strength = 5000
			u.max_strength = 5000
			GameState.add_unit(u)

		# Starting tech: era-appropriate.
		_grant_starter_tech(c)

	# Initialize neutral relations.
	for a in GameState.countries.keys():
		for b in GameState.countries.keys():
			if a == b: continue
			GameState.set_relations(a, b, 0)

func _pick_traits(pool: Array, n: int) -> Array[String]:
	var out: Array[String] = []
	if pool.size() == 0: return out
	var copy := pool.duplicate()
	copy.shuffle()
	for i in range(min(n, copy.size())):
		out.append(String(copy[i]))
	return out

## Major rivers as polylines in (lon, lat). Converted to world coords on demand
## and rendered by MapView as cyan streams. Source-to-mouth ordering.
const RIVERS_LONLAT: Array = [
	# Nile
	[[31.5, 30.0], [31.5, 27.0], [33.0, 24.0], [33.0, 20.0], [32.0, 16.0], [32.0, 10.0], [30.5, 2.5]],
	# Amazon
	[[-50.0, -0.5], [-55.0, -2.0], [-62.0, -3.5], [-68.0, -4.0], [-73.0, -4.5], [-77.0, -6.5]],
	# Mississippi
	[[-89.5, 29.0], [-91.0, 33.0], [-91.0, 37.0], [-91.5, 42.0], [-93.0, 45.0], [-95.0, 47.5]],
	# Danube
	[[29.5, 45.0], [26.0, 44.0], [22.0, 44.5], [19.0, 45.5], [15.0, 48.0], [10.0, 48.0], [8.2, 48.0]],
	# Rhine
	[[4.2, 52.0], [6.5, 50.5], [7.5, 49.5], [8.0, 47.5]],
	# Volga
	[[48.0, 46.0], [46.0, 50.0], [44.0, 54.0], [42.0, 57.0], [36.0, 57.0]],
	# Don
	[[40.0, 47.0], [42.0, 50.0], [43.0, 53.0], [40.0, 55.0]],
	# Yangtze
	[[121.5, 31.5], [118.0, 31.5], [112.0, 30.5], [106.0, 29.5], [100.0, 29.0], [94.0, 32.0]],
	# Huang He (Yellow)
	[[118.0, 37.5], [114.0, 35.0], [110.0, 35.0], [105.0, 36.0], [100.0, 35.0], [96.0, 34.0]],
	# Ganges
	[[89.0, 23.0], [86.0, 24.5], [83.0, 25.5], [79.0, 27.0], [77.0, 29.0]],
	# Indus
	[[67.0, 24.0], [69.0, 27.0], [71.0, 31.0], [73.0, 34.0], [76.0, 35.0]],
	# Tigris / Euphrates merged
	[[48.5, 30.0], [46.0, 31.5], [44.0, 33.0], [41.0, 36.0], [38.0, 38.5]],
	# Mekong
	[[106.5, 10.5], [105.5, 13.0], [104.0, 16.0], [102.0, 18.0], [100.0, 20.5], [97.0, 23.0]],
	# Congo
	[[12.5, -6.0], [18.0, -4.0], [22.0, -2.0], [25.0, 0.0], [28.0, 1.5]],
	# Niger
	[[7.5, 4.5], [5.0, 8.5], [0.0, 11.0], [-5.0, 13.0], [-10.0, 12.0]],
	# Ob
	[[70.0, 66.5], [72.0, 62.0], [75.0, 58.0], [77.0, 54.0], [79.0, 50.0]],
	# Lena
	[[125.0, 72.0], [125.0, 68.0], [125.0, 64.0], [120.0, 60.0], [108.0, 54.0]],
]

## Caches rivers converted to world coords. Built once on first request.
var _rivers_world: Array = []

func rivers_world() -> Array:
	if not _rivers_world.is_empty():
		return _rivers_world
	for poly in RIVERS_LONLAT:
		var out := PackedVector2Array()
		for pt in poly:
			var lon: float = float(pt[0])
			var lat: float = float(pt[1])
			var x: float = (lon + 180.0) / 360.0 * GameState.MAP_W
			var y: float = (90.0 - lat) / 180.0 * GameState.MAP_H
			out.append(Vector2(x, y))
		_rivers_world.append(out)
	return _rivers_world

func _starter_unit_for(era: String) -> String:
	match era:
		"antiquity": return "levy"
		"medieval": return "men_at_arms"
		"renaissance": return "pikemen"
		"industrial": return "line_infantry"
		"modern": return "riflemen"
	return "levy"

func _grant_starter_tech(c: Country) -> void:
	var era_order := ["antiquity", "medieval", "renaissance", "industrial", "modern"]
	var idx: int = era_order.find(c.era)
	if idx < 0: idx = 0
	for tech_id in GameState.tech_tree.keys():
		var t: Dictionary = GameState.tech_tree[tech_id]
		var tera: String = String(t.get("era", "antiquity"))
		var tidx: int = era_order.find(tera)
		if tidx >= 0 and tidx < idx:
			c.researched_techs.append(tech_id)
